In [33]:
#import libraries

import pandas as pd

In [34]:
#Load dataset

df=pd.read_csv("D:\Karishma\Data analysis classes\projects\customer churn analysis\customer_churn_messy_dataset.csv")

In [35]:
#view data

df.head()

,CustomerID,TenureMonths,MonthlyCharges,ContractType,InternetService,PaymentMethod,Churn
0,CUST110179,20.0,110.54,Month-to-month,No,Electronic check,No
1,CUST109988,46.0,43.86,Month-to-month,Fiber optic,Electronic check,No
2,CUST109553,32.0,51.47,One year,DSL,Bank transfer,yes
3,CUST109859,24.0,39.7,month to month,DSL,NaN,No
4,CUST107698,15.0,85.41,One year,Fiber optic,Credit card,Yes

In [36]:
#shape of dataset

df.shape

(11100, 7)

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11100 entries, 0 to 11099
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   CustomerID       11100 non-null  object
 1   TenureMonths     10331 non-null  float64
 2   MonthlyCharges   10562 non-null  object
 3   ContractType     10563 non-null  object
 4   InternetService  10548 non-null  object
 5   PaymentMethod    10553 non-null  object
 6   Churn            10568 non-null  object
dtypes: float64(1), object(6)
memory usage: 607.2+ KB

In [38]:
#check missing values

df.isnull().sum()

CustomerID           0
TenureMonths       769
MonthlyCharges     538
ContractType       537
InternetService    552
PaymentMethod      547
Churn              532
dtype: int64

In [40]:
#check duplicates

df.duplicated().sum()
df.drop_duplicates(inplace=True)
df.shape

(11000, 7)

In [41]:
#strip spaces for column values

for col in df.select_dtypes(include='object').columns:
    df[col]=df[col].str.strip()

In [42]:
df.dtypes

CustomerID          object
TenureMonths       float64
MonthlyCharges      object
ContractType        object
InternetService     object
PaymentMethod       object
Churn               object
dtype: object

In [43]:
#convert customer id to string

df['CustomerID']=df['CustomerID'].astype('string')

In [50]:
#ensure numeric columns

# Convert numeric columns safely
df['TenureMonths'] = pd.to_numeric(df['TenureMonths'], errors='coerce')
df['MonthlyCharges'] = pd.to_numeric(df['MonthlyCharges'], errors='coerce')

# Handle missing values
df['TenureMonths'] = df['TenureMonths'].fillna(df['TenureMonths'].median()).astype('int64')
df['MonthlyCharges'] = df['MonthlyCharges'].fillna(df['MonthlyCharges'].median())

In [51]:
#convert categorical columns

categorical_col= ['ContractType','InternetService','PaymentMethod','Churn']

for col in categorical_col:
    df[col]=df[col].astype('category')
    df[col].fillna(df[col].mode(),inplace=True)

C:\Users\karishma thakare\AppData\Local\Temp\ipykernel_10956\2628315556.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode(),inplace=True)
C:\Users\karishma thakare\AppData\Local\Temp\ipykernel_10956\2628315556.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode(),inplace=True)
C:\Users\karishma thakare\AppData\Local\Temp\ipykernel_10956\2628315556.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode(),inplace=True)
C:\Users\karishma thakare\AppData\Local\Temp\ipykernel_10956\2628315556.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].fillna(df[col].mode(),inplace=True)

In [73]:
# Create Churn_Flag safely from messy data
df['Churn_Flag'] = (
    df['Churn']
    .astype(str)        # handle NaN and non-string values
    .str.strip()        # remove extra spaces
    .str.lower()        # normalize casing
    .eq('yes')          # True if churn == 'yes'
    .astype('int8')     # convert True/False to 1/0
)

In [74]:
# Check if any values failed to map
df[df['Churn_Flag'].isna()]['Churn'].unique()

array([], dtype=object)

In [75]:
df[['Churn', 'Churn_Flag']].head()

  Churn  Churn_Flag
0    no           0
1    no           0
2   yes           1
3    no           0
4   yes           1

In [76]:
df.dtypes

CustomerID         string[python]
TenureMonths                int64
MonthlyCharges            float64
ContractType             category
InternetService          category
PaymentMethod            category
Churn                      object
Churn_Flag                   int8
dtype: object

In [77]:
df.to_csv("D:\Karishma\Data analysis classes\projects\customer churn analysis\cleaned_Customer_Churn_Dataset.csv")